### ISSUE TITLE
PSR2 formatting

### ISSUE THREAD

**Issue by mikkeyalias** [bmewburn/intelephense#46]
```php
require_once (CWD . '/config/config.php');
```
Error: "Space before opening parenthesis of function call prohibited"

```php
if ($val == '1') {
    echo '1';
}
else {
    echo '2';
}
```
Error: "Expected 1 space after closing brace; newline found"

```php
<?php
$_lang = Array('info' => 'Info', );
?>
```
Error: "End of line character is invalid; expected "\n" but found "\r\n""
Error: "PHP keywords must be lowercase; expected "array" but found "Array""
Error: "A closing tag is not permitted at the end of a PHP file"

**Comment by mikkeyalias** [comment]
```php
switch ($id) {
    case 1 :
        echo 1;
        break;
    case 2 :
        echo 2;
        break;
    default :
        echo 'def';
        break;
}
```
Error: "There must be no space before the colon in a CASE statement"

**Comment by jjtriff** [comment]
I'm having the same problem with formatting. Is there a way to suspend the formattingProvider of this extension so another one can take on this??

**Comment by bmewburn** [comment]
resolved in v0.8.0

**Comment by mikkeyalias** [comment]
Not fixed.
```php
require_once (CWD . '/config/config.php');
```
Error: "Space before opening parenthesis of function call prohibited" (NOT FIXED)

Result should be:
```php
require_once(CWD . '/config/config.php');
```


```php
<?php
$_lang = Array('info' => 'Info', );
?>
```
Error: "End of line character is invalid; expected "\n" but found "\r\n"" (NOT FIXED)
Error: "PHP keywords must be lowercase; expected "array" but found "Array"" (fixed)
Error: "A closing tag is not permitted at the end of a PHP file" (NOT FIXED)

Result should be:
```php
<?php
$_lang = array('info' => 'Info', );
```

**Comment by bmewburn** [comment]
require_once bug resolved in v0.8.1. The `Array` and closing tag issue have test cases that pass. The EOL should be handled by the editor.

**Comment by mikkeyalias** [comment]
Array > array - ok

Error: "End of line character is invalid; expected "\n" but found "\r\n"" (NOT FIXED)
> The EOL char should be handled by the editor.
Ok I can set "files.eol": "\n", but if "\r\n" already exists in file it should be converted to "\n"

```php
<?php
$_lang = array('info' => 'Info', );
?>
```
Error: "A closing tag is not permitted at the end of a PHP file" (NOT FIXED)
After format code:
```php
<?php
$_lang = array('info' => 'Info', );
?>
```
Result should be:
```php
<?php
$_lang = array('info' => 'Info', );
```

Also, PSR2 - "All PHP files MUST end with a single blank line.".

Another PSR2 formatting bug:
"The PHP constants true, false, and null MUST be in lower case."
```php
<?php
$_lang = array(
    'q' => TRUE,
    'w' => FALSE,
    'e' => NULL,
);
```
After format code:
```php
<?php
$_lang = array(
    'q' => TRUE,
    'w' => FALSE,
    'e' => NULL,
);
```
Result should be:
```php
<?php
$_lang = array(
    'q' => true,
    'w' => false,
    'e' => null,
);
```

**Comment by mikkeyalias** [comment]
Code:
```php
print      ($e->getMessage());
```

After format code:
```php
print ($e->getMessage());
```

Correct version:
```php
print($e->getMessage());
```

**Comment by mikkeyalias** [comment]
Code:
```php
$printer->setDebug(($border == 1) ? 'P' : '');
```

After format code:
```php
$printer->setDebug( ($border == 1) ? 'P' : '');
```
"ERROR: Space after opening parenthesis of function call prohibited"

Correct version:
```php
$printer->setDebug(($border == 1) ? 'P' : '');
```

**Comment by jjasoncool** [comment]
Code:

`${$surveyCalculate[$key]["SN"] . "_ADD_C"}`

After format code:

$ {
    $surveyCalculate[$key]["SN"] . "_ADD_C"
}

This is dynamic variables :[dynamic variables](url)
I am not sure it is correct or not. but this is confused me.Because this not found in PSR-2 rules.

**Comment by bmewburn** [comment]
related #65

**Comment by bmewburn** [comment]
v0.8.4 should solve most of these listed here. I have a test case for the closing tag passing so need more info on that one. I'm still considering the EOL \r\n an editor issue for now.
